---
title: "Appendix"
author: "Rena Zhong"
date: "11/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyverse)
library(kableExtra)
library(tidyr)
library(xtable)
```


```{r load, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
hate_crime <- read_csv("hate_crime.csv")
```

### Appendix

```{r rem-var, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Removed Variables"}
# list of removed variables from hate crimes
rv <- data.frame(names(hate_crime[, c(3,4,5,6,14,15,16,17,18,20,21,23)]))
kable(xtable(rv), caption = "removed variables")%>%
  kable_classic(full_width = F, html_font = "Cambria")
```

```{r anti-maj, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Anti-Majority"}
Anti_Majority <- c("Anti-White", "Anti-Catholic", "Anti-Protestant","Anti-Heterosexual",
                   "Anti-Male", "Anti-Eastern Orthodox (Russian, Greek, Other)",
                   "Anti-Physical Disability;Anti-White","Anti-Male", 
                   "Anti-Male;Anti-White", "Anti-Catholic;Anti-Protestant")
kable(Anti_Majority, caption = "Anti-majority")%>%
  kable_classic(full_width = F, html_font = "Cambria")
```

